title: Casey Cruz # your name (or website title) here
logo: "/images/Image.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About: 
  <br>I am currently enrolled as a senior at St. Mary's College of Maryland. In May of 2024 I will graduate with a Bachelors of Science in computer science. Once I graduate I will be looking for a career track starting position involving data analysis, coding, and deployment into the real world. I am open to opportunities in diverse industries, including business and defense.<br>
  
  <a href="https://caseycruz23.github.io/Resume/CaseyCruzResume2024-2.pdf">View My Resume</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
